# Test with pytest

name: Pytest tests

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

env:
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  DEFAULT_ADMIN_LOGIN: ${{ secrets.DEFAULT_ADMIN_LOGIN }}
  DEFAULT_ADMIN_PASSWORD: ${{ secrets.DEFAULT_ADMIN_PASSWORD }}
  
jobs:
  build:
    name: Tests with pytest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare dependencies
        run: pip install -r requirements.txt

      - name: Initialize database with default admin
        run: python create_initial_superuser.py

      - name: Workflow debugging
        run: |
          ls -ha
          env
        
      - name: Test
        working-directory: app
        run: pytest
